### ISSUE TITLE
Use iconify/json icons, e.g. `<i-mdi-close-circle />`

### ISSUE THREAD

**Issue by eXConf** [AlexKVal/vite-vue-tut-#4]

**Comment by eXConf** [comment]
@AlexKVal did your write this example just out of your head or was it real syntax? I can't see such one on the framework's site - https://icon-sets.iconify.design/mdi/close-circle/

**Comment by AlexKVal** [comment]
@eXConf 
This is from here
<img width="300" alt="Screenshot 2022-08-23 at 18 41 23" src="https://user-images.githubusercontent.com/847572/186227760-c52de4f3-01ff-4758-90c5-4fc4a34c1b94.png">

though, notice, that the project imports the entire set, not a part of it
<img width="362" alt="Screenshot 2022-08-23 at 18 41 39" src="https://user-images.githubusercontent.com/847572/186227848-8c145502-a487-4656-819c-b18cc388f77f.png">

so that could explain the difference.

**Comment by AlexKVal** [comment]
This looks good to me
<img width="395" alt="image" src="https://user-images.githubusercontent.com/847572/186228730-8afee268-4ab3-43d4-a6b9-e739cd852b3b.png">
